export default function useCreateSmartBox() {
    let par = {
        gender_receiver: "",
        name_receiver: "",
        email_receiver: "",
        phone_receiver: "",
        address_receiver: "",
        gender_shipper: "",
        name_shipper: "",
        email_shipper: "",
        phone_shipper: "",
        address_shipper: "",
        weight: "",
        quantity: "",
        description: "",
        subdistrict_receiver: "",
        district_receiver: "",
        postalcode_receiver: "",
        subdistrict_shipper: "",
        district_shipper: "",
        postalcode_shipper: "",
        duration: "",
        shipping_costs: "",
        province_receiver: "",
        city_receiver: "",
        province_shipper: "",
        city_shipper: "",
        district_code_shipper: "",
        district_code_receiver: "",
    }
}